### ISSUE TITLE
Dependency on numpy version

### ISSUE THREAD

**Issue by krisvanneste** [arkottke/pyrotd#7]
Dear Albert,

In your recent commit "Add optimized approach", you replaced the "interpolation" argument of the numpy percentile function with the new "method" argument, which was introduced in numpy 1.22.0. Would you consider making pyrotd independent of the numpy version, by either:
- removing the interpolation/method argument, as "linear" was and still is the default value
- checking for the numpy version, and pass the correct argument, something like:
```
if [int(val) for val in np.__version__.split('.')] < [1, 22, 0]:
    p_peak_resps = np.percentile(rotated.peak_resp, percentiles, interpolation="linear")
else:
    p_peak_resps = np.percentile(rotated.peak_resp, percentiles, method="linear")
```
Unfortunately, I depend on a slightly older numpy version (1.20.2) in my environment...

**Comment by krisvanneste** [comment]
Thank you!

**Comment by arkottke** [comment]
No problem. Thanks for pointing out the problem. I ended up using:
https://numpy.org/doc/stable/reference/generated/numpy.lib.NumpyVersion.html
to test the version.

**Comment by krisvanneste** [comment]
I will test it in the coming days.

**Comment by krisvanneste** [comment]
It works!
